on:
  pull_request:
    types:
      - closed
  repository_dispatch:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: DEV
    defaults:
      run:
        shell: bash

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with: 
        ref: ${{ github.ref }}

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v1

    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: tfplan.yml
        name: TerraformPlan

    - name: 'Apply Terraform Plan'
      run: |
        curl -X POST https://api.github.com/repos/raintreeinc/kiosk_serverless/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "Trigger", "client_payload": { "ACCESSKEY": "${{ secrets.AWS_ACCESS_KEY_ID }}", "SECRETKEY": "${{ secrets.AWS_SECRET_ACCESS_KEY }}", "ENVIRONMENT": "${{ secrets.ENVIRONMENT }}"  }}'
        # curl -X POST https://api.github.com/repos/raintreeinc/kiosk_backend/dispatches \
        #   -H 'Accept: application/vnd.github.everest-preview+json' \
        #   -u ${{ secrets.ACCESS_TOKEN }} \
        #   --data '{"event_type": "Trigger", "client_payload": { "ACCESSKEY": "${{ secrets.AWS_ACCESS_KEY_ID }}", "SECRETKEY": "${{ secrets.AWS_SECRET_ACCESS_KEY }}", "ENVIRONMENT": "${{ secrets.ENVIRONMENT }}"  }}'
        # curl -X POST https://api.github.com/repos/raintreeinc/kiosk_frontend/dispatches \
        #   -H 'Accept: application/vnd.github.everest-preview+json' \
        #   -u ${{ secrets.ACCESS_TOKEN }} \
        #   --data '{"event_type": "Trigger", "client_payload": { "ACCESSKEY": "${{ secrets.AWS_ACCESS_KEY_ID }}", "SECRETKEY": "${{ secrets.AWS_SECRET_ACCESS_KEY }}", "ENVIRONMENT": "${{ secrets.ENVIRONMENT }}"  }}'    
        # curl -X POST https://api.github.com/repos/raintreeinc/raintree_appsync_backend/dispatches \
        #   -H 'Accept: application/vnd.github.everest-preview+json' \
        #   -u ${{ secrets.ACCESS_TOKEN }} \
        #   --data '{"event_type": "Trigger", "client_payload": { "ACCESSKEY": "${{ secrets.AWS_ACCESS_KEY_ID }}", "SECRETKEY": "${{ secrets.AWS_SECRET_ACCESS_KEY }}", "ENVIRONMENT": "${{ secrets.ENVIRONMENT }}"  }}' 

        #  curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: token GITHUB_TOKEN" https://api.github.com/repos/OWNER/kiosk_backend/actions/workflows/.github/workflows/dotnet.yml/dispatches  -d '{"ref":"development"}'


        
        export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
        export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        terraform init
        terraform apply tfplan
