on:
  pull_request:
    types:
      - opened

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    environment: DEV
    defaults:
      run:
        shell: bash

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2 
      with: 
        ref: ${{ github.ref }}

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v1

    - name: 'Create Terraform Plan Artifact for Apply'
      run: |
        curl -X POST https://api.github.com/repos/raintreeinc/kiosk_serverless/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "pong", "client_payload": { "ACCESSKEY": "${{ secrets.AWS_ACCESS_KEY_ID }}", "SECRETKEY": "${{ secrets.AWS_SECRET_ACCESS_KEY }}"  }}'
        export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
        export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        terraform init
        terraform plan -out src/tfplan

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: TerraformPlan
        path: src/tfplan
        retention-days: 1
